---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalgreenhouse/bosh-windows-stemcell-builder

inputs:
  - name: stemcell-builder
  - name: bosh-windows-stemcell

run:
  path: stemcell-builder/scripts/run_bwats.rb

params:
  IAAS:
  ACCOUNT_JSON:
  BOSH_CA_CERT:
  BOSH_CLIENT:
  BOSH_CLIENT_SECRET:
  DIRECTOR_IP:
  DIRECTOR_UUID:
  STEMCELL_NAME:
  STEMCELL_PATH:
  AZ: z1
  VM_TYPE: large
  NETWORK: default
