---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalgreenhouse/packer-base

inputs:
  - name: stemcell-builder
  - name: base-amis
  - name: compiled-agent
  - name: version

outputs:
  - name: bosh-windows-stemcell
  - name: amis
  - name: sha

run:
  path: stemcell-builder/scripts/create-aws-stemcell.rb

params:
  OS_VERSION: windows2012R2
  AWS_ACCESS_KEY:
  AWS_SECRET_KEY:
