---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalgreenhouse/bosh-windows-stemcell-builder

inputs:
  - name: stemcell-builder
  - name: base-gcp-image
  - name: version
  - name: windows-stemcell-dependencies

outputs:
  - name: bosh-windows-stemcell

run:
  path: stemcell-builder/scripts/create-gcp-stemcell.rb

params:
  OS_VERSION: windows2012R2
  ACCOUNT_JSON:
