---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalgreenhouse/packer-base

inputs:
  - name: version
  - name: compiled-agent
  - name: stemcell-builder
  - name: windows-stemcell-dependencies
  - name: base-iso

outputs:
  - name: bosh-windows-stemcell

run:
  path: powershell
  args:
    - '-c'
    - |
    cd stemcell-builder
    bundle install
    rake build:vsphere


params:
  OUTPUT_DIR: replace-me
  ISO_CHECKSUM_TYPE: replace-me
  ISO_CHECKSUM: replace-me
  MEMSIZE: replace-me
  NUMVCPUS: replace-me
  REMOTE_HOST: replace-me
  REMOTE_PORT: replace-me
  REMOTE_DATASTORE: replace-me
  REMOTE_CACHE_DATASTORE: replace-me
  REMOTE_CACHE_DIRECTORY: replace-me
  REMOTE_USERNAME: replace-me
  REMOTE_PASSWORD: replace-me
  ADMINISTRATOR_PASSWORD: replace-me
  PRODUCT_KEY: ""
  OWNER: ""
  ORGANIZATION: ""
  GUEST_NETWORK_ADDRESS: replace-me
  GUEST_NETWORK_MASK: replace-me
  GUEST_NETWORK_GATEWAY: replace-me
