---
platform: windows

inputs:
  - name: version
  - name: vmx-version
  - name: compiled-agent
  - name: stemcell-builder
  - name: windows-stemcell-dependencies
outputs:
  - name: bosh-windows-stemcell

run:
  path: ruby.exe
  args:
    - stemcell-builder/scripts/create-vsphere-stemcell.rb

params:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  AWS_REGION: us-east-1

  ADMINISTRATOR_PASSWORD: replace-me
  OS_VERSION: windows2012R2

  INPUT_BUCKET: "bosh-windows-stemcell-vmx"
  OUTPUT_BUCKET: "bosh-windows-stemcells-pre-release-candidate"
  VMX_CACHE_DIR: "C:\\vmx-data"

  PRODUCT_KEY:
  ORGANIZATION:
  OWNER:

